#!/usr/bin/env bash

if [ "$(uname -m)" = "x86_64" ]
then
  CELLAR=/usr/local/Cellar
else
  CELLAR=/opt/homebrew/Cellar
fi

LIBEXEC=$CELLAR/ppap/%VERSION%/libexec
JAR=$LIBEXEC/ppap-%VERSION%.jar
JAVA=$LIBEXEC/jre/bin/java

$JAVA -jar $JAR "$@"
